name: Fetch latest ilk data
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
jobs:
  buidl:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Setup
      run: npm i
    - name: Fetch latest data
      run: npm run update-ilks
    - name: Version bump if changes exist
      run: if [[ `git status --porcelain` ]]; then npm run version-bump; fi
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: "Update ilks (automated)"
        title: "Update ilks"
        delete-branch: true
