# This is a basic workflow that is manually triggered

name: Manual workflow

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  buidl:
    runs-on: ubuntu-latest
    steps:
    # Runs a single command using the runners shell
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Setup
      run: npm i
    - name: Fetch latest data
      run: cd scripts/ && node updateIlksInfo.js
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: "Update ilks (automated)"
